Location.destroy_all
Movie.destroy_all
Ticket.destroy_all
User.destroy_all

charlie_angels = Movie.create(title: "Charlie's Angels", genre: "Action", rating: "PG-13")
ford_v_ferrari = Movie.create(title: "Ford v Ferrari", genre: "Drama", rating: "PG-13")
good_liar = Movie.create(title: "The Good Liar", genre: "Drama", rating: "R")
waves = Movie.create(title: "Waves", genre: "Romance", rating: "R")
all_rise = Movie.create(title: "All Rise", genre: "Drama", rating: "R")
terminator_dark_fate = Movie.create(title: "Terminator: Dark Fate", genre: "Sci-Fi", rating: "R")
joker = Movie.create(title: "Joker", genre: "Thriller", rating: "R")
maleficent = Movie.create(title: "Maleficent: Mistress of Evil", genre: "Family", rating: "PG")
addams_family = Movie.create(title: "The Addams Family", genre: "Comedy", rating: "PG")
arctic_dogs = Movie.create(title: "Arctic Dogs", genre: "Comedy", rating: "PG")

regal_edwards = Location.create(name: "Regal Edwards")  #10
amc_studio_30 = Location.create(name: "AMC Studio 30")  #11
alamo = Location.create(name: "Alamo")    #12
studio_movie_grill = Location.create(name: "Studio Movie Grill")  #12.50
ipic = Location.create(name: "IPIC")  #13.00
rooftop_cinema = Location.create(name: "Rooftop Cinema Club") #13.50

Ticket.create(price: 10.00, time: "1:30 PM", movie: charlie_angels, location: regal_edwards)
Ticket.create(price: 11.00, time: "1:30 PM", movie: charlie_angels, location: amc_studio_30)
Ticket.create(price: 12.00, time: "1:40 PM", movie: charlie_angels, location: alamo)
Ticket.create(price: 12.50, time: "1:45 PM", movie: charlie_angels, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "1:55 PM", movie: charlie_angels, location: ipic)
Ticket.create(price: 11.00, time: "1:55 PM", movie: charlie_angels, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "1:30 PM", movie: ford_v_ferrari, location: regal_edwards)
Ticket.create(price: 11.00, time: "1:30 PM", movie: ford_v_ferrari, location: amc_studio_30)
Ticket.create(price: 12.00, time: "1:40 PM", movie: ford_v_ferrari, location: alamo)
Ticket.create(price: 12.50, time: "1:45 PM", movie: ford_v_ferrari, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "1:55 PM", movie: ford_v_ferrari, location: ipic)
Ticket.create(price: 11.00, time: "1:55 PM", movie: ford_v_ferrari, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "1:30 PM", movie: good_liar, location: regal_edwards)
Ticket.create(price: 11.00, time: "1:30 PM", movie: good_liar, location: amc_studio_30)
Ticket.create(price: 12.00, time: "1:40 PM", movie: good_liar, location: alamo)
Ticket.create(price: 12.50, time: "1:45 PM", movie: good_liar, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "1:55 PM", movie: good_liar, location: ipic)
Ticket.create(price: 11.00, time: "1:55 PM", movie: good_liar, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "1:30 PM", movie: waves, location: regal_edwards)
Ticket.create(price: 11.00, time: "1:30 PM", movie: waves, location: amc_studio_30)
Ticket.create(price: 12.00, time: "1:40 PM", movie: waves, location: alamo)
Ticket.create(price: 12.50, time: "1:45 PM", movie: waves, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "1:55 PM", movie: waves, location: ipic)
Ticket.create(price: 11.00, time: "1:55 PM", movie: waves, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "1:30 PM", movie: all_rise, location: regal_edwards)
Ticket.create(price: 11.00, time: "1:30 PM", movie: all_rise, location: amc_studio_30)
Ticket.create(price: 12.00, time: "1:40 PM", movie: all_rise, location: alamo)
Ticket.create(price: 12.50, time: "1:45 PM", movie: all_rise, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "1:55 PM", movie: all_rise, location: ipic)
Ticket.create(price: 11.00, time: "1:55 PM", movie: all_rise, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "1:30 PM", movie: terminator_dark_fate, location: regal_edwards)
Ticket.create(price: 11.00, time: "1:30 PM", movie: terminator_dark_fate, location: amc_studio_30)
Ticket.create(price: 12.00, time: "1:40 PM", movie: terminator_dark_fate, location: alamo)
Ticket.create(price: 12.50, time: "1:45 PM", movie: terminator_dark_fate, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "1:55 PM", movie: terminator_dark_fate, location: ipic)
Ticket.create(price: 11.00, time: "1:55 PM", movie: terminator_dark_fate, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "1:30 PM", movie: joker, location: regal_edwards)
Ticket.create(price: 11.00, time: "1:30 PM", movie: joker, location: amc_studio_30)
Ticket.create(price: 12.00, time: "1:40 PM", movie: joker, location: alamo)
Ticket.create(price: 12.50, time: "1:45 PM", movie: joker, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "1:55 PM", movie: joker, location: ipic)
Ticket.create(price: 11.00, time: "1:55 PM", movie: joker, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "1:30 PM", movie: maleficent, location: regal_edwards)
Ticket.create(price: 11.00, time: "1:30 PM", movie: maleficent, location: amc_studio_30)
Ticket.create(price: 12.00, time: "1:40 PM", movie: maleficent, location: alamo)
Ticket.create(price: 12.50, time: "1:45 PM", movie: maleficent, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "1:55 PM", movie: maleficent, location: ipic)
Ticket.create(price: 11.00, time: "1:55 PM", movie: maleficent, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "1:30 PM", movie: addams_family, location: regal_edwards)
Ticket.create(price: 11.00, time: "1:30 PM", movie: addams_family, location: amc_studio_30)
Ticket.create(price: 12.00, time: "1:40 PM", movie: addams_family, location: alamo)
Ticket.create(price: 12.50, time: "1:45 PM", movie: addams_family, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "1:55 PM", movie: addams_family, location: ipic)
Ticket.create(price: 11.00, time: "1:55 PM", movie: addams_family, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "1:30 PM", movie: arctic_dogs, location: regal_edwards)
Ticket.create(price: 11.00, time: "1:30 PM", movie: arctic_dogs, location: amc_studio_30)
Ticket.create(price: 12.00, time: "1:40 PM", movie: arctic_dogs, location: alamo)
Ticket.create(price: 12.50, time: "1:45 PM", movie: arctic_dogs, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "1:55 PM", movie: arctic_dogs, location: ipic)
Ticket.create(price: 11.00, time: "1:55 PM", movie: arctic_dogs, location: rooftop_cinema)

#####################################################################################################

Ticket.create(price: 10.00, time: "3:30 PM", movie: charlie_angels, location: regal_edwards)
Ticket.create(price: 11.00, time: "3:30 PM", movie: charlie_angels, location: amc_studio_30)
Ticket.create(price: 12.00, time: "3:40 PM", movie: charlie_angels, location: alamo)
Ticket.create(price: 12.50, time: "3:45 PM", movie: charlie_angels, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "3:55 PM", movie: charlie_angels, location: ipic)
Ticket.create(price: 11.00, time: "3:55 PM", movie: charlie_angels, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "3:30 PM", movie: ford_v_ferrari, location: regal_edwards)
Ticket.create(price: 11.00, time: "3:30 PM", movie: ford_v_ferrari, location: amc_studio_30)
Ticket.create(price: 12.00, time: "3:40 PM", movie: ford_v_ferrari, location: alamo)
Ticket.create(price: 12.50, time: "3:45 PM", movie: ford_v_ferrari, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "3:55 PM", movie: ford_v_ferrari, location: ipic)
Ticket.create(price: 11.00, time: "3:55 PM", movie: ford_v_ferrari, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "3:30 PM", movie: good_liar, location: regal_edwards)
Ticket.create(price: 11.00, time: "3:30 PM", movie: good_liar, location: amc_studio_30)
Ticket.create(price: 12.00, time: "3:40 PM", movie: good_liar, location: alamo)
Ticket.create(price: 12.50, time: "3:45 PM", movie: good_liar, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "3:55 PM", movie: good_liar, location: ipic)
Ticket.create(price: 11.00, time: "3:55 PM", movie: good_liar, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "3:30 PM", movie: waves, location: regal_edwards)
Ticket.create(price: 11.00, time: "3:30 PM", movie: waves, location: amc_studio_30)
Ticket.create(price: 12.00, time: "3:40 PM", movie: waves, location: alamo)
Ticket.create(price: 12.50, time: "3:45 PM", movie: waves, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "3:55 PM", movie: waves, location: ipic)
Ticket.create(price: 11.00, time: "3:55 PM", movie: waves, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "3:30 PM", movie: all_rise, location: regal_edwards)
Ticket.create(price: 11.00, time: "3:30 PM", movie: all_rise, location: amc_studio_30)
Ticket.create(price: 12.00, time: "3:40 PM", movie: all_rise, location: alamo)
Ticket.create(price: 12.50, time: "3:45 PM", movie: all_rise, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "3:55 PM", movie: all_rise, location: ipic)
Ticket.create(price: 11.00, time: "3:55 PM", movie: all_rise, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "3:30 PM", movie: terminator_dark_fate, location: regal_edwards)
Ticket.create(price: 11.00, time: "3:30 PM", movie: terminator_dark_fate, location: amc_studio_30)
Ticket.create(price: 12.00, time: "3:40 PM", movie: terminator_dark_fate, location: alamo)
Ticket.create(price: 12.50, time: "3:45 PM", movie: terminator_dark_fate, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "3:55 PM", movie: terminator_dark_fate, location: ipic)
Ticket.create(price: 11.00, time: "3:55 PM", movie: terminator_dark_fate, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "3:30 PM", movie: joker, location: regal_edwards)
Ticket.create(price: 11.00, time: "3:30 PM", movie: joker, location: amc_studio_30)
Ticket.create(price: 12.00, time: "3:40 PM", movie: joker, location: alamo)
Ticket.create(price: 12.50, time: "3:45 PM", movie: joker, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "3:55 PM", movie: joker, location: ipic)
Ticket.create(price: 11.00, time: "3:55 PM", movie: joker, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "3:30 PM", movie: maleficent, location: regal_edwards)
Ticket.create(price: 11.00, time: "3:30 PM", movie: maleficent, location: amc_studio_30)
Ticket.create(price: 12.00, time: "3:40 PM", movie: maleficent, location: alamo)
Ticket.create(price: 12.50, time: "3:45 PM", movie: maleficent, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "3:55 PM", movie: maleficent, location: ipic)
Ticket.create(price: 11.00, time: "3:55 PM", movie: maleficent, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "3:30 PM", movie: addams_family, location: regal_edwards)
Ticket.create(price: 11.00, time: "3:30 PM", movie: addams_family, location: amc_studio_30)
Ticket.create(price: 12.00, time: "3:40 PM", movie: addams_family, location: alamo)
Ticket.create(price: 12.50, time: "3:45 PM", movie: addams_family, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "3:55 PM", movie: addams_family, location: ipic)
Ticket.create(price: 11.00, time: "3:55 PM", movie: addams_family, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "3:30 PM", movie: arctic_dogs, location: regal_edwards)
Ticket.create(price: 11.00, time: "3:30 PM", movie: arctic_dogs, location: amc_studio_30)
Ticket.create(price: 12.00, time: "3:40 PM", movie: arctic_dogs, location: alamo)
Ticket.create(price: 12.50, time: "3:45 PM", movie: arctic_dogs, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "3:55 PM", movie: arctic_dogs, location: ipic)
Ticket.create(price: 11.00, time: "3:55 PM", movie: arctic_dogs, location: rooftop_cinema)

#################################################################################################

Ticket.create(price: 10.00, time: "5:30 PM", movie: charlie_angels, location: regal_edwards)
Ticket.create(price: 11.00, time: "5:30 PM", movie: charlie_angels, location: amc_studio_30)
Ticket.create(price: 12.00, time: "5:40 PM", movie: charlie_angels, location: alamo)
Ticket.create(price: 12.50, time: "5:45 PM", movie: charlie_angels, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "5:55 PM", movie: charlie_angels, location: ipic)
Ticket.create(price: 11.00, time: "5:55 PM", movie: charlie_angels, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "5:30 PM", movie: ford_v_ferrari, location: regal_edwards)
Ticket.create(price: 11.00, time: "5:30 PM", movie: ford_v_ferrari, location: amc_studio_30)
Ticket.create(price: 12.00, time: "5:40 PM", movie: ford_v_ferrari, location: alamo)
Ticket.create(price: 12.50, time: "5:45 PM", movie: ford_v_ferrari, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "5:55 PM", movie: ford_v_ferrari, location: ipic)
Ticket.create(price: 11.00, time: "5:55 PM", movie: ford_v_ferrari, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "5:30 PM", movie: good_liar, location: regal_edwards)
Ticket.create(price: 11.00, time: "5:30 PM", movie: good_liar, location: amc_studio_30)
Ticket.create(price: 12.00, time: "5:40 PM", movie: good_liar, location: alamo)
Ticket.create(price: 12.50, time: "5:45 PM", movie: good_liar, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "5:55 PM", movie: good_liar, location: ipic)
Ticket.create(price: 11.00, time: "5:55 PM", movie: good_liar, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "5:30 PM", movie: waves, location: regal_edwards)
Ticket.create(price: 11.00, time: "5:30 PM", movie: waves, location: amc_studio_30)
Ticket.create(price: 12.00, time: "5:40 PM", movie: waves, location: alamo)
Ticket.create(price: 12.50, time: "5:45 PM", movie: waves, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "5:55 PM", movie: waves, location: ipic)
Ticket.create(price: 11.00, time: "5:55 PM", movie: waves, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "5:30 PM", movie: all_rise, location: regal_edwards)
Ticket.create(price: 11.00, time: "5:30 PM", movie: all_rise, location: amc_studio_30)
Ticket.create(price: 12.00, time: "5:40 PM", movie: all_rise, location: alamo)
Ticket.create(price: 12.50, time: "5:45 PM", movie: all_rise, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "5:55 PM", movie: all_rise, location: ipic)
Ticket.create(price: 11.00, time: "5:55 PM", movie: all_rise, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "5:30 PM", movie: terminator_dark_fate, location: regal_edwards)
Ticket.create(price: 11.00, time: "5:30 PM", movie: terminator_dark_fate, location: amc_studio_30)
Ticket.create(price: 12.00, time: "5:40 PM", movie: terminator_dark_fate, location: alamo)
Ticket.create(price: 12.50, time: "5:45 PM", movie: terminator_dark_fate, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "5:55 PM", movie: terminator_dark_fate, location: ipic)
Ticket.create(price: 11.00, time: "5:55 PM", movie: terminator_dark_fate, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "5:30 PM", movie: joker, location: regal_edwards)
Ticket.create(price: 11.00, time: "5:30 PM", movie: joker, location: amc_studio_30)
Ticket.create(price: 12.00, time: "5:40 PM", movie: joker, location: alamo)
Ticket.create(price: 12.50, time: "5:45 PM", movie: joker, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "5:55 PM", movie: joker, location: ipic)
Ticket.create(price: 11.00, time: "5:55 PM", movie: joker, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "5:30 PM", movie: maleficent, location: regal_edwards)
Ticket.create(price: 11.00, time: "5:30 PM", movie: maleficent, location: amc_studio_30)
Ticket.create(price: 12.00, time: "5:40 PM", movie: maleficent, location: alamo)
Ticket.create(price: 12.50, time: "5:45 PM", movie: maleficent, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "5:55 PM", movie: maleficent, location: ipic)
Ticket.create(price: 11.00, time: "5:55 PM", movie: maleficent, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "5:30 PM", movie: addams_family, location: regal_edwards)
Ticket.create(price: 11.00, time: "5:30 PM", movie: addams_family, location: amc_studio_30)
Ticket.create(price: 12.00, time: "5:40 PM", movie: addams_family, location: alamo)
Ticket.create(price: 12.50, time: "5:45 PM", movie: addams_family, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "5:55 PM", movie: addams_family, location: ipic)
Ticket.create(price: 11.00, time: "5:55 PM", movie: addams_family, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "5:30 PM", movie: arctic_dogs, location: regal_edwards)
Ticket.create(price: 11.00, time: "5:30 PM", movie: arctic_dogs, location: amc_studio_30)
Ticket.create(price: 12.00, time: "5:40 PM", movie: arctic_dogs, location: alamo)
Ticket.create(price: 12.50, time: "5:45 PM", movie: arctic_dogs, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "5:55 PM", movie: arctic_dogs, location: ipic)
Ticket.create(price: 11.00, time: "5:55 PM", movie: arctic_dogs, location: rooftop_cinema)

################################################################################################

Ticket.create(price: 10.00, time: "7:30 PM", movie: charlie_angels, location: regal_edwards)
Ticket.create(price: 11.00, time: "7:30 PM", movie: charlie_angels, location: amc_studio_30)
Ticket.create(price: 12.00, time: "7:40 PM", movie: charlie_angels, location: alamo)
Ticket.create(price: 12.50, time: "7:45 PM", movie: charlie_angels, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "7:55 PM", movie: charlie_angels, location: ipic)
Ticket.create(price: 11.00, time: "7:55 PM", movie: charlie_angels, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "7:30 PM", movie: ford_v_ferrari, location: regal_edwards)
Ticket.create(price: 11.00, time: "7:30 PM", movie: ford_v_ferrari, location: amc_studio_30)
Ticket.create(price: 12.00, time: "7:40 PM", movie: ford_v_ferrari, location: alamo)
Ticket.create(price: 12.50, time: "7:45 PM", movie: ford_v_ferrari, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "7:55 PM", movie: ford_v_ferrari, location: ipic)
Ticket.create(price: 11.00, time: "7:55 PM", movie: ford_v_ferrari, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "7:30 PM", movie: good_liar, location: regal_edwards)
Ticket.create(price: 11.00, time: "7:30 PM", movie: good_liar, location: amc_studio_30)
Ticket.create(price: 12.00, time: "7:40 PM", movie: good_liar, location: alamo)
Ticket.create(price: 12.50, time: "7:45 PM", movie: good_liar, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "7:55 PM", movie: good_liar, location: ipic)
Ticket.create(price: 11.00, time: "7:55 PM", movie: good_liar, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "7:30 PM", movie: waves, location: regal_edwards)
Ticket.create(price: 11.00, time: "7:30 PM", movie: waves, location: amc_studio_30)
Ticket.create(price: 12.00, time: "7:40 PM", movie: waves, location: alamo)
Ticket.create(price: 12.50, time: "7:45 PM", movie: waves, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "7:55 PM", movie: waves, location: ipic)
Ticket.create(price: 11.00, time: "7:55 PM", movie: waves, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "7:30 PM", movie: all_rise, location: regal_edwards)
Ticket.create(price: 11.00, time: "7:30 PM", movie: all_rise, location: amc_studio_30)
Ticket.create(price: 12.00, time: "7:40 PM", movie: all_rise, location: alamo)
Ticket.create(price: 12.50, time: "7:45 PM", movie: all_rise, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "7:55 PM", movie: all_rise, location: ipic)
Ticket.create(price: 11.00, time: "7:55 PM", movie: all_rise, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "7:30 PM", movie: terminator_dark_fate, location: regal_edwards)
Ticket.create(price: 11.00, time: "7:30 PM", movie: terminator_dark_fate, location: amc_studio_30)
Ticket.create(price: 12.00, time: "7:40 PM", movie: terminator_dark_fate, location: alamo)
Ticket.create(price: 12.50, time: "7:45 PM", movie: terminator_dark_fate, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "7:55 PM", movie: terminator_dark_fate, location: ipic)
Ticket.create(price: 11.00, time: "7:55 PM", movie: terminator_dark_fate, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "7:30 PM", movie: joker, location: regal_edwards)
Ticket.create(price: 11.00, time: "7:30 PM", movie: joker, location: amc_studio_30)
Ticket.create(price: 12.00, time: "7:40 PM", movie: joker, location: alamo)
Ticket.create(price: 12.50, time: "7:45 PM", movie: joker, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "7:55 PM", movie: joker, location: ipic)
Ticket.create(price: 11.00, time: "7:55 PM", movie: joker, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "7:30 PM", movie: maleficent, location: regal_edwards)
Ticket.create(price: 11.00, time: "7:30 PM", movie: maleficent, location: amc_studio_30)
Ticket.create(price: 12.00, time: "7:40 PM", movie: maleficent, location: alamo)
Ticket.create(price: 12.50, time: "7:45 PM", movie: maleficent, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "7:55 PM", movie: maleficent, location: ipic)
Ticket.create(price: 11.00, time: "7:55 PM", movie: maleficent, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "7:30 PM", movie: addams_family, location: regal_edwards)
Ticket.create(price: 11.00, time: "7:30 PM", movie: addams_family, location: amc_studio_30)
Ticket.create(price: 12.00, time: "7:40 PM", movie: addams_family, location: alamo)
Ticket.create(price: 12.50, time: "7:45 PM", movie: addams_family, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "7:55 PM", movie: addams_family, location: ipic)
Ticket.create(price: 11.00, time: "7:55 PM", movie: addams_family, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "7:30 PM", movie: arctic_dogs, location: regal_edwards)
Ticket.create(price: 11.00, time: "7:30 PM", movie: arctic_dogs, location: amc_studio_30)
Ticket.create(price: 12.00, time: "7:40 PM", movie: arctic_dogs, location: alamo)
Ticket.create(price: 12.50, time: "7:45 PM", movie: arctic_dogs, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "7:55 PM", movie: arctic_dogs, location: ipic)
Ticket.create(price: 11.00, time: "7:55 PM", movie: arctic_dogs, location: rooftop_cinema)

#################################################################################################

Ticket.create(price: 10.00, time: "9:30 PM", movie: charlie_angels, location: regal_edwards)
Ticket.create(price: 11.00, time: "9:30 PM", movie: charlie_angels, location: amc_studio_30)
Ticket.create(price: 12.00, time: "9:40 PM", movie: charlie_angels, location: alamo)
Ticket.create(price: 12.50, time: "9:45 PM", movie: charlie_angels, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "9:55 PM", movie: charlie_angels, location: ipic)
Ticket.create(price: 11.00, time: "9:55 PM", movie: charlie_angels, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "9:30 PM", movie: ford_v_ferrari, location: regal_edwards)
Ticket.create(price: 11.00, time: "9:30 PM", movie: ford_v_ferrari, location: amc_studio_30)
Ticket.create(price: 12.00, time: "9:40 PM", movie: ford_v_ferrari, location: alamo)
Ticket.create(price: 12.50, time: "9:45 PM", movie: ford_v_ferrari, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "9:55 PM", movie: ford_v_ferrari, location: ipic)
Ticket.create(price: 11.00, time: "9:55 PM", movie: ford_v_ferrari, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "9:30 PM", movie: good_liar, location: regal_edwards)
Ticket.create(price: 11.00, time: "9:30 PM", movie: good_liar, location: amc_studio_30)
Ticket.create(price: 12.00, time: "9:40 PM", movie: good_liar, location: alamo)
Ticket.create(price: 12.50, time: "9:45 PM", movie: good_liar, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "9:55 PM", movie: good_liar, location: ipic)
Ticket.create(price: 11.00, time: "9:55 PM", movie: good_liar, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "9:30 PM", movie: waves, location: regal_edwards)
Ticket.create(price: 11.00, time: "9:30 PM", movie: waves, location: amc_studio_30)
Ticket.create(price: 12.00, time: "9:40 PM", movie: waves, location: alamo)
Ticket.create(price: 12.50, time: "9:45 PM", movie: waves, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "9:55 PM", movie: waves, location: ipic)
Ticket.create(price: 11.00, time: "9:55 PM", movie: waves, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "9:30 PM", movie: all_rise, location: regal_edwards)
Ticket.create(price: 11.00, time: "9:30 PM", movie: all_rise, location: amc_studio_30)
Ticket.create(price: 12.00, time: "9:40 PM", movie: all_rise, location: alamo)
Ticket.create(price: 12.50, time: "9:45 PM", movie: all_rise, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "9:55 PM", movie: all_rise, location: ipic)
Ticket.create(price: 11.00, time: "9:55 PM", movie: all_rise, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "9:30 PM", movie: terminator_dark_fate, location: regal_edwards)
Ticket.create(price: 11.00, time: "9:30 PM", movie: terminator_dark_fate, location: amc_studio_30)
Ticket.create(price: 12.00, time: "9:40 PM", movie: terminator_dark_fate, location: alamo)
Ticket.create(price: 12.50, time: "9:45 PM", movie: terminator_dark_fate, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "9:55 PM", movie: terminator_dark_fate, location: ipic)
Ticket.create(price: 11.00, time: "9:55 PM", movie: terminator_dark_fate, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "9:30 PM", movie: joker, location: regal_edwards)
Ticket.create(price: 11.00, time: "9:30 PM", movie: joker, location: amc_studio_30)
Ticket.create(price: 12.00, time: "9:40 PM", movie: joker, location: alamo)
Ticket.create(price: 12.50, time: "9:45 PM", movie: joker, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "9:55 PM", movie: joker, location: ipic)
Ticket.create(price: 11.00, time: "9:55 PM", movie: joker, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "9:30 PM", movie: maleficent, location: regal_edwards)
Ticket.create(price: 11.00, time: "9:30 PM", movie: maleficent, location: amc_studio_30)
Ticket.create(price: 12.00, time: "9:40 PM", movie: maleficent, location: alamo)
Ticket.create(price: 12.50, time: "9:45 PM", movie: maleficent, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "9:55 PM", movie: maleficent, location: ipic)
Ticket.create(price: 11.00, time: "9:55 PM", movie: maleficent, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "9:30 PM", movie: addams_family, location: regal_edwards)
Ticket.create(price: 11.00, time: "9:30 PM", movie: addams_family, location: amc_studio_30)
Ticket.create(price: 12.00, time: "9:40 PM", movie: addams_family, location: alamo)
Ticket.create(price: 12.50, time: "9:45 PM", movie: addams_family, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "9:55 PM", movie: addams_family, location: ipic)
Ticket.create(price: 11.00, time: "9:55 PM", movie: addams_family, location: rooftop_cinema)

Ticket.create(price: 10.00, time: "9:30 PM", movie: arctic_dogs, location: regal_edwards)
Ticket.create(price: 11.00, time: "9:30 PM", movie: arctic_dogs, location: amc_studio_30)
Ticket.create(price: 12.00, time: "9:40 PM", movie: arctic_dogs, location: alamo)
Ticket.create(price: 12.50, time: "9:45 PM", movie: arctic_dogs, location: studio_movie_grill)
Ticket.create(price: 13.00, time: "9:55 PM", movie: arctic_dogs, location: ipic)
Ticket.create(price: 11.00, time: "9:55 PM", movie: arctic_dogs, location: rooftop_cinema)